### ISSUE TITLE
Unable to set power on ATA device

### ISSUE THREAD

**Issue by droid44** [vilppuvuorinen/pymelcloud#12]
I have been trying to write some code to switch an ATA device on when an alarm is triggered from a temperature sensor. I can login and read information from the unit but I am unable to set the power. I am working on the theory that it is a boolean value, but whenever I try and write to it I get: AttributeError: can't set attribute

**Comment by vilppuvuorinen** [comment]
It sounds like you are trying to assign the property directly:

```
ata.power = new_value
```

You need to use the `set` method instead. It would look something like this:

```
await ata.set({ 'power': new_value })
```

**Comment by droid44** [comment]
Thank you for the pointer, I will give it a try...

**Comment by droid44** [comment]
I have finished the project and the air con now responds to the temperature sensor perfectly.

Thank you for your help and the amazing library!
