### ISSUE TITLE
Recent firmware update results in occasional 0kWh cumulative energy readings

### ISSUE THREAD

**Issue by KingJ** [vilppuvuorinen/pymelcloud#13]
Originally reported at https://github.com/home-assistant/core/issues/60341.

My Mitsubishi Electric MSZ-EF air-to-air heat pump units recently received a firmware update for their MAC-567IF WiFi interfaces. Although this finally seems to allow the units to receive commands in real time (rather than polling MELCloud every minute), it also seems to result in the reported cumulative energy consumption dropping to zero for a few minutes, and then returning to the normal value. As Home Assistant uses pmelcloud for its MELCloud integration, this drop to zero wildly skew's Home Assistant's Energy statistics for individual devices, as every drop to zero and subsequent return to normal results in that much energy being considered as consumed. For example, so far today this means Home Assistant thinks the unit has consumed 5,803.6kWh of energy whereas in reality total consumption today has increased from 965.4kWh to 967.7kWh (i.e. an increase of 2.3kWh).

Unfortunately I cannot find any references to the firmware version that is now on the MAC-567IF WiFi interfaces - I was offered it as an update a few days ago and accepted it. It is the first update firmware update I have had for these units since installing them last year.

**Comment by jasimancas** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/15717847/143482600-00aeb39c-9aee-47c1-a0c2-cd0d33968927.png)
![image](https://user-images.githubusercontent.com/15717847/143482639-6b46503b-0ac9-4e0b-b4e4-46eac37d5441.png)
15.000KW/h its impossible.

**Comment by vilppuvuorinen** [comment]
I need some help diagnosing coming up with a solution because I haven't been offered this firmware upgrade at least yet.

1. Is the value during the error an exact zero?
2. Are the transitions instant without any intermediate incorrect values?

**Comment by jasimancas** [comment]
Occurs apparently every 5 minutes

![image](https://user-images.githubusercontent.com/15717847/143558804-896fb11f-8479-40d2-a760-76ac4814c72d.png)

**Comment by vilppuvuorinen** [comment]
I wonder if something like #16 would work. The basic idea is to keep track of the last non-zero energy consumed value and return it instead of a zero. What do you two think?

I tried to simulate the new firmware by randomly faking zero values and I did get consistent non-zero values with this approach.

**Comment by kiansp** [comment]
Seems to work! I copied out your new ata_device.py and replaced the one inside the  homeassistant container. Not a lot of energy use so far today, but the value has changed a bit and there are no 0 kWh readings recorded.

![image](https://user-images.githubusercontent.com/3425804/143678560-6b50b1f0-03b1-403f-8c14-27d446d15f00.png)

**Comment by KingJ** [comment]
> I need some help diagnosing coming up with a solution because I haven't been offered this firmware upgrade at least yet.
> 
> 1. Is the value during the error an exact zero?
> 2. Are the transitions instant without any intermediate incorrect values?

It's a little tricky to say for sure as i'm just reading the values out of Home Assistant rather than using the library directly, but;

1. The value appears to be exactly zero.
2. The transition is instant - it goes immediately to 0 without going to any other intermediate values. When it returns to normal, it goes straight back to the previous value or slightly higher (i.e accounting for an actual increase of cumulative consumption during the time it was zero'd out).

Unlike @jasimancas, my drops to zero seem to mostly occur when making changes (i.e. to the target temperature or mode)  rather than at a regular interval.

**Comment by vilppuvuorinen** [comment]
I've merged the changes. I'll try to get the changes released and a PR open towards home-assistant during this weekend.

**Comment by konkrog** [comment]
This should solve the issue.... It seems it it not yet available from HA... When will it be available for regular use in HA?

**Comment by vilppuvuorinen** [comment]
It has usually taken less than a week between merge to dev and release. For some reason there haven't been new releases in 11 days now which makes it hard to predict how fast this change is going to make it into a release.
