### ISSUE TITLE
wifi_signal not working from device.py 

### ISSUE THREAD

**Issue by zaklex** [vilppuvuorinen/pymelcloud#5]
wifi_signal not working from device.py 
Probably because there are no WifiSignalStrength in /Device/Get?id=
It only exists in /User/ListDevices

my /Device/Get?id

> CoreMaintenanceRequired: false
> DefaultCoolingSetTemperature: 22
> DefaultHeatingSetTemperature: 21
> DeviceID: 0000
> DeviceType: 3
> EffectiveFlags: 0
> ErrorCode: 8000
> ErrorMessage: null
> FilterMaintenanceRequired: false
> HasPendingCommand: false
> HideOutdoorTemperature: false
> HideRoomTemperature: false
> HideSupplyTemperature: false
> LastCommunication: "2020-07-06T16:21:11.56"
> LocalIPAddress: null
> Name: null
> NextCommunication: "2020-07-06T16:22:11.56"
> NightPurgeMode: false
> NumberOfFanSpeeds: 4
> Offline: false
> OperationMode: 7
> OutdoorTemperature: 31
> Power: false
> RoomCO2Level: 0
> RoomTemperature: 31
> Scene: null
> SceneOwner: null
> SetFanSpeed: 4
> SetTemperature: null
> SupplyTemperature: null
> TemperatureIncrementOverride: 0
> VentilationMode: 0

**Comment by vilppuvuorinen** [comment]
Ah, sorry. That's what I get for fixing something that's not broken. Could you create a PR with a valid `/Device/Get` json in the samples dir (and a fix if you don't mind)?

**Comment by vilppuvuorinen** [comment]
Fixed in #6.
