### ISSUE TITLE
Example does not work as written

### ISSUE THREAD

**Issue by psaffrey** [vilppuvuorinen/pymelcloud#7]
Thanks very much for producing this library, which is exactly what I was looking for. 

I wonder if you could tidy up the example a little so that it runs as-written? The code in the example it just gives the message

`SyntaxError: 'await' outside function`

You're using the `asyncio` functionality (which was new to me) and I spent a good while wallowing around in tutorials before I got this code to run - I think you need to wrap it in an asyncio loop or similar. Even then if you're not careful you get messages like `Unclosed client session`. Maybe a "best practice" example for how to run the basic login workflow would be appropriate?

**Comment by vilppuvuorinen** [comment]
That's a good point. The examples do actually work without modifications in an interactive interpreter given the interpreter can handle async. I think I used IPython or aioconsole, but my memory is a bit hazy on the details. This isn't immediately obvious and I think the bare minimum would be to mention the requirement above the example.

My use case for this library is to get home-assistant connected to MELCloud. Therefore the API is pretty much a 1:1 match to how home-assistant integrations work.

I think you have currently the best idea how the documentation should be improved. Would you mind creating a PR with the improvements?

**Comment by aradovan** [comment]
@psaffrey please share your updates or example code modified. I'm facing the same issue and I've just started reading about asyncio xD

**Comment by aradovan** [comment]
> @psaffrey please share your updates or example code modified. I'm facing the same issue and I've just started reading about asyncio xD

Ok, I've made it work. I've added the "import asyncio" and then wrote the example code into

"async def example():"

And out of the function:

loop  =  asyncio.get_event_loop () 
loop.run_until_complete (example ())

And it worked.

**Comment by psaffrey** [comment]
Thanks for the poke, I made a PR for this: https://github.com/vilppuvuorinen/pymelcloud/pull/8

**Comment by vilppuvuorinen** [comment]
I assume I can just close this now.
