### ISSUE TITLE
[Discussion] Exterior temperature and Humidity 

### ISSUE THREAD

**Issue by lopesdasilva** [vilppuvuorinen/pymelcloud#9]
Hey, Thanks for this project!

I was checking the api call on the melcloud app and I saw that they have this exterior temperature and interior temperature.
Do you think it's coming from actually readings from the exterior unit or just some forecast form some external service from Mitsubishi ? 
![image](https://user-images.githubusercontent.com/1013126/117284985-5c623c00-ae5f-11eb-9550-702e98da3a98.png)

thanks

**Comment by lopesdasilva** [comment]
I can answer my self.. 
I've changed my unit location on the settings and the WeatherObservations object immediately changed...
![image](https://user-images.githubusercontent.com/1013126/117285502-fe822400-ae5f-11eb-8d3a-614245fcf473.png)
so no exterior readings 👎

**Comment by vilppuvuorinen** [comment]
Some devices do seem to have temperature sensors on the exterior units. I think it was the Ecodan product line, but my memory is quite hazy here. Even when present they have been pretty useless. The sensors I remember seeing had 1°C accuracy and were updated every ten minutes or so.

Please let me know if you find something interesting from the API. I have just a single air-to-air unit to work with and I think I've managed to dig up everything interesting there was to find.
